export interface TableConfig {
    tableName: string;
    allowedFields: string[];
    requiredFields: string[];
    defaultSort?: string;
    select?: string;
    parentFilterField?: string | string[];
}

export const TABLE_CONFIGS: Record<string, TableConfig> = {
    users: {
        tableName: 'users',
        allowedFields: ['email', 'display_name', 'stripe_customer_id', 'subscription_status', 'subscription_plan', 'onboarding_complete'],
        requiredFields: ['email'],
        defaultSort: 'created_at',
    },
    business_profiles: {
        tableName: 'business_profiles',
        allowedFields: [
            'user_id',
            'business_name',
            'business_state',
            'industry',
            'current_revenue_range',
            'strengths',
            'weaknesses',
            'risk_tolerance',
            'hours_per_week',
            'monthly_budget_range',
            'no_go_constraints',
            'target_audience',
            'existing_assets',
            'additional_context',
            'raw_answers',
        ],
        requiredFields: ['user_id'],
        defaultSort: 'created_at',
        parentFilterField: 'user_id',
    },
    founder_profiles: {
        tableName: 'founder_profiles',
        allowedFields: ['user_id', 'team_size', 'va_count', 'calendar_blocks_available', 'timezone'],
        requiredFields: ['user_id'],
        defaultSort: 'created_at',
        parentFilterField: 'user_id',
    },
    decisions: {
        tableName: 'decisions',
        allowedFields: ['user_id', 'business_profile_id', 'status', 'chosen_strategy_id', 'thread_id', 'chosen_at'],
        requiredFields: ['user_id'],
        defaultSort: 'created_at',
        select: '*, business_profiles:business_profile_id(business_name)',
        parentFilterField: 'user_id',
    },
    strategy_options: {
        tableName: 'strategy_options',
        allowedFields: [
            'decision_id',
            'rank',
            'archetype',
            'thesis',
            'channel_focus',
            'offer_shape',
            'first_7_day_plan',
            'risks',
            'mitigations',
            'kpis',
            'decision_score',
            'confidence',
            'score_breakdown',
            'assumptions',
            'raw_ai_output',
        ],
        requiredFields: ['decision_id', 'rank', 'archetype', 'thesis'],
        defaultSort: 'created_at',
        parentFilterField: 'decision_id',
    },
    execution_contracts: {
        tableName: 'execution_contracts',
        allowedFields: ['user_id', 'decision_id', 'strategy_id', 'locked_kpi', 'weekly_deliverable', 'calendar_blocks'],
        requiredFields: ['user_id', 'decision_id', 'strategy_id', 'locked_kpi', 'weekly_deliverable', 'calendar_blocks'],
        defaultSort: 'signed_at',
        parentFilterField: 'user_id',
    },
    weekly_cycles: {
        tableName: 'weekly_cycles',
        allowedFields: [
            'user_id',
            'execution_contract_id',
            'week_number',
            'status',
            'kpi_target',
            'kpi_actual',
            'board_meeting_notes',
            'kill_list',
            'keep_list',
            'double_list',
            'thread_id',
            'completed_at',
        ],
        requiredFields: ['user_id', 'week_number'],
        defaultSort: 'created_at',
        parentFilterField: 'user_id',
    },
    deliverables: {
        tableName: 'deliverables',
        allowedFields: [
            'weekly_cycle_id',
            'user_id',
            'department',
            'title',
            'size',
            'status',
            'content',
            'red_team_passed',
            'red_team_feedback',
        ],
        requiredFields: ['user_id', 'weekly_cycle_id', 'department', 'title', 'size'],
        defaultSort: 'created_at',
        parentFilterField: 'weekly_cycle_id',
    },
    tasks: {
        tableName: 'tasks',
        allowedFields: [
            'deliverable_id',
            'weekly_cycle_id',
            'user_id',
            'title',
            'description',
            'assignee',
            'status',
            'due_date',
            'sort_order',
        ],
        requiredFields: ['user_id', 'weekly_cycle_id', 'title'],
        defaultSort: 'sort_order',
        parentFilterField: 'weekly_cycle_id',
    },
    assets: {
        tableName: 'assets',
        allowedFields: ['deliverable_id', 'user_id', 'asset_type', 'title', 'content', 'storage_path'],
        requiredFields: ['user_id', 'title', 'asset_type'],
        defaultSort: 'created_at',
        parentFilterField: 'user_id',
    },
    assumptions: {
        tableName: 'assumptions',
        allowedFields: ['strategy_option_id', 'weekly_cycle_id', 'assumption_text', 'category', 'risk_level'],
        requiredFields: ['assumption_text'],
        defaultSort: 'created_at',
        parentFilterField: ['strategy_option_id', 'weekly_cycle_id'],
    },
    generation_jobs: {
        tableName: 'generation_jobs',
        allowedFields: ['user_id', 'job_type', 'reference_id', 'status', 'attempts', 'max_attempts', 'error_message', 'started_at', 'completed_at'],
        requiredFields: ['user_id', 'job_type'],
        defaultSort: 'created_at',
        parentFilterField: 'user_id',
    },
    chat_conversations: {
        tableName: 'chat_conversations',
        allowedFields: ['user_id', 'execution_contract_id', 'title'],
        requiredFields: ['user_id', 'title'],
        defaultSort: 'created_at',
        parentFilterField: 'user_id',
    },
    chat_messages: {
        tableName: 'chat_messages',
        allowedFields: ['conversation_id', 'role', 'content', 'reaction', 'task_updates'],
        requiredFields: ['conversation_id', 'role', 'content'],
        defaultSort: 'created_at',
        parentFilterField: 'conversation_id',
    },
};
