'use client';

import Link from 'next/link';
import { motion } from 'framer-motion';
import {
  Crown,
  ArrowLeft,
  MessageSquare,
  Route,
  Briefcase,
  Package,
  CalendarCheck,
  RotateCcw,
  ChevronRight,
  Zap,
} from 'lucide-react';
import styles from './guide.module.css';

const steps = [
  {
    num: '01',
    icon: MessageSquare,
    title: 'The Questionnaire',
    body: 'Everything starts with understanding your current reality. Our AI conducts a deep-dive interview to extract key metrics about your business, team size, budget constraints, and risk tolerance.',
    tip: 'Be ruthlessly honest. AI cannot optimize what you hide from it. Overstating revenue or underestimating time constraints will lead to unrealistic strategies.',
    label: 'INPUT PHASE',
  },
  {
    num: '02',
    icon: Route,
    title: 'Strategy Selection',
    body: 'Based on your interview, the AI generates 3 distinct strategic paths. Each maps to an execution archetype — Aggressive Growth, Steady Optimization, or Survival Mode. You review the thesis and lock into one path.',
    tip: "Don't suffer from shiny object syndrome. Pick a strategy and commit. Give it at least 2–4 weeks of dedicated execution before considering a pivot.",
    label: 'DECISION PHASE',
  },
  {
    num: '03',
    icon: Briefcase,
    title: 'Your Office Dashboard',
    body: 'Your Office is your command center. It tracks your Active Strategy, your locked KPI (the one metric that matters right now), and the current Weekly Deliverable.',
    tip: 'Check your Office daily to ground your focus. When distractions arise, ask yourself: "Does this move my Locked KPI?" If no, discard it.',
    label: 'COMMAND CENTER',
  },
  {
    num: '04',
    icon: Package,
    title: 'The Ship Pack',
    body: 'The Ship Pack breaks your strategy down into weekly execution chunks. It lists exact action items generated by the AI for the current week. Complete tasks, check them off, and keep notes on blockers.',
    tip: 'Action Items should rarely exceed 3–4 hours of deep work each. If a task feels overwhelming, break it into sub-tasks on your own calendar.',
    label: 'EXECUTION PHASE',
  },
  {
    num: '05',
    icon: CalendarCheck,
    title: 'Weekly Board Meeting',
    body: "At the end of your week, hold a Board Meeting with the AI. You'll evaluate task completion, grade your execution quality (A to F), and report unforeseen challenges. Detailed feedback ensures the next Ship Pack is better calibrated.",
    tip: "The AI uses your grade to adjust future strategy. If you give yourself an 'A' while actually slacking, the model will attribute missed KPIs to the strategy itself — not you.",
    label: 'REVIEW PHASE',
  },
  {
    num: '06',
    icon: RotateCcw,
    title: 'Iteration & Pivot',
    body: 'If you successfully hit milestones — or if a strategy proves completely unviable — you can Reset your Strategy. This returns you to the drawing board to plot your next major phase of growth.',
    tip: 'A reset is not failure. Founders who iterate fast outcompete those who grind against a broken thesis.',
    label: 'ITERATION PHASE',
  },
];

export default function PlaybookPage() {
  return (
    <div className={styles.page}>

      {/* ── Nav ── */}
      <nav className={styles.nav}>
        <div className={styles.navInner}>
          <Link href="/" className={styles.navBrand}>
            <div className={styles.logoMark}>
              <Crown size={16} />
            </div>
            <span className={styles.navBrandText}>THE BILLIONAIRE BROTHER</span>
          </Link>
          <div className={styles.navLinks}>
            <Link href="/" className={styles.navLink}>HOME</Link>
            <Link href="/#pricing" className={styles.navLink}>PRICING</Link>
            <Link href="/guide" className={`${styles.navLink} ${styles.navLinkActive}`}>PLAYBOOK</Link>
          </div>
          <Link href="/auth" className={styles.navCta}>
            ACCESS TERMINAL →
          </Link>
        </div>
      </nav>

      {/* ── Hero ── */}
      <section className={styles.hero}>
        <div className={styles.heroInner}>
          <div className={styles.heroBreadcrumb}>
            <Link href="/" className={styles.breadcrumbLink}>
              <ArrowLeft size={13} />
              Back to Home
            </Link>
            <span className={styles.breadcrumbSep}>/</span>
            <span className={styles.breadcrumbCurrent}>Playbook</span>
          </div>

          <div className={styles.heroChip}>
            <span className={styles.chipDot} />
            <span>OPERATIONAL FRAMEWORK // DEREK_V2.0</span>
          </div>

          <h1 className={styles.heroTitle}>
            The Billionaire<br />
            <span className={styles.heroGold}>Brother Playbook.</span>
          </h1>
          <p className={styles.heroSub}>
            A step-by-step framework to maximize your leverage, build compounding
            strategies, and execute like a seasoned founder. No fluff. Just the protocol.
          </p>

          <div className={styles.heroMeta}>
            <div className={styles.metaChip}>
              <Zap size={12} />
              <span>6 PHASES</span>
            </div>
            <div className={styles.metaChip}>
              <ChevronRight size={12} />
              <span>WEEKLY CADENCE</span>
            </div>
            <div className={styles.metaChip}>
              <Crown size={12} />
              <span>AI-POWERED</span>
            </div>
          </div>
        </div>
      </section>

      {/* ── Steps timeline ── */}
      <section className={styles.timeline}>
        <div className={styles.timelineInner}>
          {steps.map((step, i) => {
            const Icon = step.icon;
            const isLast = i === steps.length - 1;
            return (
              <motion.div 
                key={step.num} 
                className={styles.step}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-50px" }}
                transition={{ duration: 0.5, delay: i * 0.1, ease: 'easeOut' }}
              >
                {/* Connector line */}
                {!isLast && <div className={styles.connector} />}

                {/* Left: number + icon */}
                <div className={styles.stepLeft}>
                  <div className={styles.stepIconWrap}>
                    <Icon size={18} />
                  </div>
                  <span className={styles.stepNum}>{step.num}</span>
                </div>

                {/* Right: content */}
                <div className={styles.stepContent}>
                  <div className={styles.stepMeta}>
                    <span className={styles.stepLabel}>{step.label}</span>
                  </div>
                  <h2 className={styles.stepTitle}>{step.title}</h2>
                  <p className={styles.stepBody}>{step.body}</p>

                  <div className={styles.proTip}>
                    <span className={styles.proTipBadge}>PRO TIP</span>
                    <p className={styles.proTipText}>{step.tip}</p>
                  </div>
                </div>
              </motion.div>
            );
          })}
        </div>
      </section>

      {/* ── CTA Banner ── */}
      <section className={styles.ctaBanner}>
        <div className={styles.ctaInner}>
          <div className={styles.ctaChip}>
            <span className={styles.chipDot} />
            <span>SYSTEM READY</span>
          </div>
          <h2 className={styles.ctaTitle}>Ready to Execute?</h2>
          <p className={styles.ctaSub}>
            Derek is standing by. Start with the questionnaire and receive your first
            brutal, honest strategy within minutes.
          </p>
          <Link href="/auth" className={styles.ctaBtn} id="playbook-cta">
            START FREE QUESTIONNAIRE →
          </Link>
        </div>
      </section>

      {/* ── Footer ── */}
      <footer className={styles.footer}>
        <div className={styles.footerInner}>
          <Link href="/" className={styles.footerBrand}>
            <Crown size={14} />
            <span>THE BILLIONAIRE BROTHER</span>
          </Link>
          <div className={styles.footerLinks}>
            <Link href="/framework" className={styles.footerLink}>Terms of Service</Link>
            <Link href="/framework" className={styles.footerLink}>Privacy Policy</Link>
            <Link href="/auth" className={styles.footerLink}>System Status</Link>
          </div>
          <span className={styles.footerCopy}>
            © {new Date().getFullYear()} The Billionaire Brother. All rights reserved.
          </span>
        </div>
      </footer>
    </div>
  );
}
