'use client';

import { useState, useMemo } from 'react';
import {
    HelpCircle,
    Search,
    ChevronDown,
    Copy,
    CheckCheck,
    BookOpen,
    Zap,
    CreditCard,
    Settings,
    Mail,
    MessageSquare,
    Rocket,
    Users,
    BarChart3,
    Lightbulb,
    ExternalLink,
} from 'lucide-react';
import styles from './help.module.css';

/* ──────────────────────────────────────────────
   DATA
   ────────────────────────────────────────────── */

const FAQ_CATEGORIES = [
    {
        id: 'getting-started',
        label: 'Getting Started',
        icon: Rocket,
        color: 'gold',
        faqs: [
            {
                q: 'What is Billionaire Brother and what does it do?',
                a: 'Billionaire Brother is an AI-powered business growth OS. It conducts a deep intake interview to understand your business, then builds a personalised revenue strategy, daily action steps, and automated email campaigns — all tailored to your specific situation and goals.',
            },
            {
                q: 'How do I start after signing up?',
                a: 'After signing in, you\'ll land on your Dashboard. Click "Start Interview" (or visit Your Office) to complete your AI intake. This foundational interview powers everything else on the platform — your Strategy Brief, Playbook, and Action Steps are all generated from it.',
            },
            {
                q: 'How long does the onboarding interview take?',
                a: 'Most users complete the intake interview in 20–35 minutes. We recommend doing it in one sitting when you\'re not distracted — the quality of your answers directly affects the quality of your strategy.',
            },
            {
                q: 'Can I redo or update my interview answers?',
                a: 'Yes. Go to Your Office and use the "Reset Strategy" button. This clears your current strategy and lets you re-run the intake. Use this if your business focus has significantly changed.',
            },
        ],
    },
    {
        id: 'strategy',
        label: 'Strategy & Playbook',
        icon: BookOpen,
        color: 'purple',
        faqs: [
            {
                q: 'What is the Strategy Brief?',
                a: 'Your Strategy Brief is a living document — generated by the AI after your intake — that outlines your core revenue opportunity, ideal customer profile, primary offer positioning, and 90-day sprint focus. It updates as you check in weekly.',
            },
            {
                q: 'What is the Playbook and how do I use it?',
                a: 'The Playbook is your structured growth curriculum. It breaks down each phase of the Revenue Velocity Machine framework into actionable modules. Work through it sequentially for best results, or jump to the section most relevant to your current bottleneck.',
            },
            {
                q: 'How often should I update my strategy?',
                a: 'We recommend a Weekly Check-in (Board Meeting) every 7 days. This keeps your Action Steps fresh and lets the AI recalibrate based on your results. Strategies that go unchecked for 30+ days may drift out of alignment with your actual progress.',
            },
            {
                q: 'My strategy doesn\'t feel quite right — what should I do?',
                a: 'First, try the Weekly Check-in to give the AI updated context. If that doesn\'t fix it, reset your strategy from Your Office and be more specific during the re-interview. The AI improves significantly with richer, more detailed input.',
            },
        ],
    },
    {
        id: 'email',
        label: 'Email Campaigns',
        icon: Mail,
        color: 'blue',
        faqs: [
            {
                q: 'How does the email campaign generator work?',
                a: 'The email generator uses your Strategy Brief and Playbook context to write full multi-email sequences in your brand voice. Each campaign is structured around the Revenue Velocity Machine\'s funnel architecture — Awareness → Consideration → Conversion.',
            },
            {
                q: 'How many emails can I generate per campaign?',
                a: 'Standard campaigns generate 5–7 emails per sequence. Brother-tier members can generate extended sequences of up to 15 emails. You can regenerate individual emails you\'re not happy with without redoing the whole campaign.',
            },
            {
                q: 'Can I edit the emails after they\'re generated?',
                a: 'Yes — each generated email can be edited inline before you export or copy it. Click on any email block to open the editor. Changes are saved locally per session; we recommend copying to your email platform promptly.',
            },
            {
                q: 'Why did my email generation fail?',
                a: 'Generation failures are usually due to: (1) hitting your monthly prompt limit — check Settings → Token Usage, (2) a temporary AI service interruption — wait 60 seconds and retry, or (3) a missing strategy context — complete your intake interview first.',
            },
        ],
    },
    {
        id: 'billing',
        label: 'Billing & Plans',
        icon: CreditCard,
        color: 'green',
        faqs: [
            {
                q: 'What plans are available?',
                a: 'We offer two plans: **Founder ($79/mo)** — full access to all features with standard prompt limits, and **Brother (invite-only)** — expanded limits, priority generation, and early access to new features. Visit the Upgrade page for current pricing details.',
            },
            {
                q: 'How do I use a promo code?',
                a: 'Go to Settings → Have a Promo Code? Enter your code in the input field and click Apply. Valid codes will immediately unlock access — no payment required. If your code isn\'t working, check for spaces or typos, and make sure you\'re on the free tier.',
            },
            {
                q: 'What happens when I hit my token limit?',
                a: 'When you reach 80% of your monthly token budget, you\'ll enter Degrade Mode — AI responses become shorter and less detailed. At 100%, all AI generation is paused until your monthly reset date. Your data and strategy are never deleted.',
            },
            {
                q: 'How do I cancel my subscription?',
                a: 'Go to Settings → Billing → Manage Billing. This opens the Stripe customer portal where you can cancel, pause, or modify your subscription. Cancellations take effect at the end of your current billing period.',
            },
            {
                q: 'Can I get a refund?',
                a: 'We offer a 7-day satisfaction guarantee on your first month. If the platform isn\'t delivering value, email support within 7 days of your initial charge for a full refund. After 7 days, refunds are handled case-by-case.',
            },
        ],
    },
    {
        id: 'account',
        label: 'Account & Settings',
        icon: Settings,
        color: 'amber',
        faqs: [
            {
                q: 'How do I change my display name?',
                a: 'Display name changes are coming in a future update. Currently your name is set during the intake interview. To update it, reset your strategy from Your Office and complete the intake again.',
            },
            {
                q: 'I forgot my password — how do I reset it?',
                a: 'On the sign-in page, click "Forgot password?" and enter your email. You\'ll receive a reset link within a few minutes. Check your spam folder if it doesn\'t arrive. The link expires after 60 minutes.',
            },
            {
                q: 'How do I delete my account?',
                a: 'To permanently delete your account and all associated data, email us at support@billionairebrother.com with the subject "Account Deletion Request." We\'ll process it within 48 hours and confirm when complete.',
            },
        ],
    },
    {
        id: 'performance',
        label: 'Performance & Results',
        icon: BarChart3,
        color: 'gold',
        faqs: [
            {
                q: 'How quickly should I expect to see results?',
                a: 'Most users see measurable momentum (leads, conversations, or revenue movement) within 30–45 days of consistent platform use. The system is built for compound growth — results accelerate as you complete more weekly check-ins and execute more action steps.',
            },
            {
                q: 'What if my market is highly specialised or niche?',
                a: 'The AI is designed to handle niche markets. Be as specific as possible in your intake about your industry, ICP, and offer. The more context you provide, the more accurate and actionable your strategy will be.',
            },
            {
                q: 'How does the Decision Score work?',
                a: 'Your Decision Score (0–100) reflects the quality and completeness of your strategic decisions across the platform. It\'s calculated from your intake depth, weekly check-in consistency, and action step completion rate. A higher score = a more refined strategy.',
            },
        ],
    },
];

const SUPPORT_MACROS = [
    {
        id: 'promo-not-working',
        label: 'Promo Code Not Working',
        icon: '🏷️',
        text: 'Hi team — my promo code isn\'t applying. Code: [CODE]. I\'m on the free tier and entered it under Settings → Have a Promo Code? Can you check if it\'s valid? Email: [YOUR EMAIL]',
    },
    {
        id: 'email-gen-failed',
        label: 'Email Generation Failed',
        icon: '✉️',
        text: 'Hi — my email campaign generation failed. I\'ve already completed the intake interview and checked my token usage (it shows [X]%). The error appeared when I tried to generate a [campaign type] sequence. Can you help? Email: [YOUR EMAIL]',
    },
    {
        id: 'strategy-wrong',
        label: 'Strategy Feels Off',
        icon: '🎯',
        text: 'Hi — my AI-generated strategy doesn\'t feel right for my business. My business is [BRIEF DESCRIPTION] and the strategy seems to focus on [WHAT IT SAYS] instead of [WHAT YOU EXPECTED]. I\'ve already tried the Weekly Check-in. Can someone review? Email: [YOUR EMAIL]',
    },
    {
        id: 'billing-question',
        label: 'Billing Question',
        icon: '💳',
        text: 'Hi — I have a billing question. My account email is [YOUR EMAIL] and my question is: [DESCRIBE YOUR QUESTION]. I can see in Settings that my status shows [STATUS]. Please advise.',
    },
    {
        id: 'cancel-request',
        label: 'Cancel Subscription',
        icon: '🔄',
        text: 'Hi — I\'d like to cancel my subscription. My account email is [YOUR EMAIL]. My main reason for cancelling: [REASON]. Please confirm the cancellation date and whether I\'ll retain access until the end of my billing period.',
    },
    {
        id: 'refund-request',
        label: 'Request a Refund',
        icon: '💰',
        text: 'Hi — I\'d like to request a refund. My account email is [YOUR EMAIL] and I signed up on [DATE]. My reason for requesting a refund: [REASON]. I understand the 7-day guarantee policy. Please advise on next steps.',
    },
    {
        id: 'account-delete',
        label: 'Delete My Account',
        icon: '🗑️',
        text: 'Account Deletion Request — Please permanently delete my account and all associated data. My account email is [YOUR EMAIL]. I confirm this is intentional and understand this action cannot be undone.',
    },
    {
        id: 'feature-request',
        label: 'Feature Request',
        icon: '💡',
        text: 'Hi — I have a feature idea for Billionaire Brother: [DESCRIBE YOUR IDEA]. Context on why this would help: [EXPLAIN CONTEXT]. I\'m currently on the [PLAN] plan. Happy to provide more detail if helpful.',
    },
];

/* ──────────────────────────────────────────────
   COMPONENTS
   ────────────────────────────────────────────── */

function FaqItem({ q, a }: { q: string; a: string }) {
    const [open, setOpen] = useState(false);

    return (
        <div className={`${styles.faqItem} ${open ? styles.faqOpen : ''}`}>
            <button className={styles.faqQuestion} onClick={() => setOpen(!open)} aria-expanded={open}>
                <span>{q}</span>
                <ChevronDown className={styles.faqChevron} size={18} />
            </button>
            {open && (
                <div className={styles.faqAnswer}>
                    <p dangerouslySetInnerHTML={{ __html: a.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>') }} />
                </div>
            )}
        </div>
    );
}

function MacroCard({ macro }: { macro: typeof SUPPORT_MACROS[0] }) {
    const [copied, setCopied] = useState(false);

    const handleCopy = () => {
        navigator.clipboard.writeText(macro.text).then(() => {
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        });
    };

    return (
        <div className={styles.macroCard}>
            <div className={styles.macroHeader}>
                <span className={styles.macroEmoji}>{macro.icon}</span>
                <span className={styles.macroLabel}>{macro.label}</span>
                <button
                    className={`${styles.macroCopyBtn} ${copied ? styles.macroCopied : ''}`}
                    onClick={handleCopy}
                    title="Copy to clipboard"
                >
                    {copied ? <CheckCheck size={14} /> : <Copy size={14} />}
                    {copied ? 'Copied!' : 'Copy'}
                </button>
            </div>
            <p className={styles.macroText}>{macro.text}</p>
        </div>
    );
}

/* ──────────────────────────────────────────────
   PAGE
   ────────────────────────────────────────────── */

export default function HelpPage() {
    const [search, setSearch] = useState('');
    const [activeCategory, setActiveCategory] = useState<string | null>(null);
    const [activeTab, setActiveTab] = useState<'faq' | 'macros'>('faq');

    const filteredCategories = useMemo(() => {
        const q = search.toLowerCase().trim();
        if (!q) {
            return activeCategory
                ? FAQ_CATEGORIES.filter(c => c.id === activeCategory)
                : FAQ_CATEGORIES;
        }
        return FAQ_CATEGORIES.map(cat => ({
            ...cat,
            faqs: cat.faqs.filter(f =>
                f.q.toLowerCase().includes(q) || f.a.toLowerCase().includes(q)
            ),
        })).filter(cat => cat.faqs.length > 0);
    }, [search, activeCategory]);

    const totalResults = filteredCategories.reduce((acc, c) => acc + c.faqs.length, 0);

    return (
        <div className={styles.page}>
            {/* ── Hero ── */}
            <div className={styles.hero}>
                <div className={styles.heroIcon}>
                    <HelpCircle size={28} />
                </div>
                <h1 className={styles.heroTitle}>Help Center</h1>
                <p className={styles.heroSub}>
                    Find answers fast, or copy a support message and send it our way.
                </p>

                {/* Search */}
                <div className={styles.searchWrap}>
                    <Search className={styles.searchIcon} size={18} />
                    <input
                        id="help-search"
                        type="search"
                        className={styles.searchInput}
                        placeholder="Search FAQs…"
                        value={search}
                        onChange={e => { setSearch(e.target.value); setActiveCategory(null); }}
                        aria-label="Search help articles"
                    />
                    {search && (
                        <span className={styles.searchCount}>
                            {totalResults} result{totalResults !== 1 ? 's' : ''}
                        </span>
                    )}
                </div>
            </div>

            {/* ── Tab switcher ── */}
            <div className={styles.tabs}>
                <button
                    id="tab-faq"
                    className={`${styles.tab} ${activeTab === 'faq' ? styles.tabActive : ''}`}
                    onClick={() => setActiveTab('faq')}
                >
                    <BookOpen size={16} />
                    FAQ
                </button>
                <button
                    id="tab-macros"
                    className={`${styles.tab} ${activeTab === 'macros' ? styles.tabActive : ''}`}
                    onClick={() => setActiveTab('macros')}
                >
                    <MessageSquare size={16} />
                    Support Macros
                </button>
            </div>

            {/* ── FAQ Tab ── */}
            {activeTab === 'faq' && (
                <div className={styles.faqLayout}>
                    {/* Category pills */}
                    {!search && (
                        <div className={styles.catPills}>
                            <button
                                className={`${styles.catPill} ${activeCategory === null ? styles.catActive : ''}`}
                                onClick={() => setActiveCategory(null)}
                            >
                                All
                            </button>
                            {FAQ_CATEGORIES.map(cat => (
                                <button
                                    key={cat.id}
                                    className={`${styles.catPill} ${activeCategory === cat.id ? styles.catActive : ''}`}
                                    onClick={() => setActiveCategory(cat.id)}
                                >
                                    <cat.icon size={14} />
                                    {cat.label}
                                </button>
                            ))}
                        </div>
                    )}

                    {filteredCategories.length === 0 ? (
                        <div className={styles.empty}>
                            <Lightbulb size={32} className={styles.emptyIcon} />
                            <p>No results for <strong>"{search}"</strong></p>
                            <p className={styles.emptyHint}>Try different keywords, or switch to Support Macros to contact us directly.</p>
                        </div>
                    ) : (
                        <div className={styles.faqSections}>
                            {filteredCategories.map(cat => (
                                <section key={cat.id} className={styles.faqSection}>
                                    <div className={`${styles.catHeader} ${styles[`cat-${cat.color}`]}`}>
                                        <cat.icon size={18} />
                                        <h2 className={styles.catTitle}>{cat.label}</h2>
                                        <span className={styles.catCount}>{cat.faqs.length}</span>
                                    </div>
                                    <div className={styles.faqList}>
                                        {cat.faqs.map((faq, i) => (
                                            <FaqItem key={i} q={faq.q} a={faq.a} />
                                        ))}
                                    </div>
                                </section>
                            ))}
                        </div>
                    )}
                </div>
            )}

            {/* ── Macros Tab ── */}
            {activeTab === 'macros' && (
                <div className={styles.macrosLayout}>
                    <div className={styles.macrosBanner}>
                        <Zap size={16} />
                        <p>
                            Copy a pre-filled message template, fill in the bracketed fields, and send to{' '}
                            <a href="mailto:support@billionairebrother.com" className={styles.supportEmail}>
                                support@billionairebrother.com
                            </a>
                        </p>
                    </div>
                    <div className={styles.macrosGrid}>
                        {SUPPORT_MACROS.map(macro => (
                            <MacroCard key={macro.id} macro={macro} />
                        ))}
                    </div>

                    {/* Direct Contact CTA */}
                    <div className={styles.contactCard}>
                        <div className={styles.contactIcon}><Users size={24} /></div>
                        <div className={styles.contactInfo}>
                            <h3>Need something else?</h3>
                            <p>Our support team typically responds within 4–8 business hours.</p>
                        </div>
                        <a
                            href="mailto:support@billionairebrother.com"
                            className="btn btn-primary"
                            id="help-contact-btn"
                        >
                            <Mail size={16} />
                            Email Support
                            <ExternalLink size={14} />
                        </a>
                    </div>
                </div>
            )}
        </div>
    );
}
