import { 
    MessageSquare, 
    Route, 
    Briefcase, 
    Package, 
    CalendarCheck, 
    Crown 
} from 'lucide-react';
import styles from './PlaybookContent.module.css';

export function PlaybookContent() {
    return (
        <div className={styles.page}>
            <header className={styles.header}>
                <h1>The Billionaire Brother Playbook</h1>
                <p>
                    A step-by-step framework to maximize your leverage, build compounding strategies, 
                    and execute like a seasoned founder.
                </p>
            </header>

            <div className={styles.timeline}>
                {/* Step 1 */}
                <div className={styles.step}>
                    <div className={styles.stepIcon}>
                        <MessageSquare size={16} />
                    </div>
                    <div className={styles.stepContent}>
                        <h2>1. The Questionnaire</h2>
                        <p>
                            Everything starts with understanding your current reality. Our AI conducts a deep-dive interview 
                            to extract key metrics about your business, team size, budget constraints, and risk tolerance.
                        </p>
                        <div className={styles.proTip}>
                            <span className={styles.proTipType}>Pro Tip</span>
                            <span className={styles.proTipText}>
                                Be ruthlessly honest. AI cannot optimize what you hide from it. 
                                Overstating revenue or underestimating time constraints will lead to unrealistic strategies.
                            </span>
                        </div>
                    </div>
                </div>

                {/* Step 2 */}
                <div className={styles.step}>
                    <div className={styles.stepIcon}>
                        <Route size={16} />
                    </div>
                    <div className={styles.stepContent}>
                        <h2>2. Strategy Selection</h2>
                        <p>
                            Based on your interview, the AI generates 3 distinct strategic paths. Each path offers a different 
                            style of execution mapping to archetypes (e.g., Aggressive Growth, Steady Optimization). 
                            You review the thesis and "sign" your contract to lock into one path.
                        </p>
                        <div className={styles.proTip}>
                            <span className={styles.proTipType}>Pro Tip</span>
                            <span className={styles.proTipText}>
                                Don't suffer from shiny object syndrome. Pick a strategy and commit. 
                                Give it at least 2 to 4 weeks of dedicated execution before considering a pivot.
                            </span>
                        </div>
                    </div>
                </div>

                {/* Step 3 */}
                <div className={styles.step}>
                    <div className={styles.stepIcon}>
                        <Briefcase size={16} />
                    </div>
                    <div className={styles.stepContent}>
                        <h2>3. Your Office Dashboard</h2>
                        <p>
                            Your Office is your command center. It tracks your Active Strategy, your locked KPI 
                            (the one metric that matters right now), and the current Weekly Deliverable.
                        </p>
                        <div className={styles.proTip}>
                            <span className={styles.proTipType}>Pro Tip</span>
                            <span className={styles.proTipText}>
                                Check your Office daily to ground your focus. When distractions arise, ask yourself: 
                                "Does this move my Locked KPI?" If no, discard it.
                            </span>
                        </div>
                    </div>
                </div>

                {/* Step 4 */}
                <div className={styles.step}>
                    <div className={styles.stepIcon}>
                        <Package size={16} />
                    </div>
                    <div className={styles.stepContent}>
                        <h2>4. The Ship Pack (Action Steps)</h2>
                        <p>
                            The Ship Pack breaks your strategy down into weekly chunks. It lists exact action items 
                            generated by the AI for the current week. Complete tasks, check them off, 
                            and keep notes on blockers.
                        </p>
                        <div className={styles.proTip}>
                            <span className={styles.proTipType}>Pro Tip</span>
                            <span className={styles.proTipText}>
                                Action Items should rarely exceed 3-4 hours of deep work each. If a task feels overwhelmingly large, 
                                try breaking it down into smaller sub-tasks on your own calendar.
                            </span>
                        </div>
                    </div>
                </div>

                {/* Step 5 */}
                <div className={styles.step}>
                    <div className={styles.stepIcon}>
                        <CalendarCheck size={16} />
                    </div>
                    <div className={styles.stepContent}>
                        <h2>5. Weekly Board Meeting</h2>
                        <p>
                            At the end of your week, hold a Board Meeting with the AI. You'll evaluate your task completion, 
                            grade your execution quality (A to F), and report any unforeseen challenges. Providing detailed 
                            feedback ensures the next Ship Pack is better calibrated.
                        </p>
                        <div className={styles.proTip}>
                            <span className={styles.proTipType}>Pro Tip</span>
                            <span className={styles.proTipText}>
                                The AI uses your grade to adjust future strategy. If you give yourself an &apos;A&apos; while actually slacking, 
                                the model will mistakenly attribute missed KPIs to the strategy itself rather than execution.
                            </span>
                        </div>
                    </div>
                </div>

                {/* Step 6 */}
                <div className={styles.step}>
                    <div className={styles.stepIcon}>
                        <Crown size={16} />
                    </div>
                    <div className={styles.stepContent}>
                        <h2>6. Iteration & Pivot</h2>
                        <p>
                            If you successfully hit milestones—or if a strategy proves completely unviable—you can Reset 
                            your Strategy. This brings you back to the drawing board to plot your next major phase of growth.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
}
