import { PolicyLayout } from '@/components/PolicyLayout';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | The Billionaire Brother',
  description: 'Review the Terms of Service for The Billionaire Brother. Understand the rules of conduct, subscription policies, and our AI strategy liability disclaimer.',
  alternates: {
    canonical: '/terms',
  },
};


export default function TermsOfService() {
  return (
    <PolicyLayout title="Terms of Service" subtitle="Effective Date: June 9, 2026">
      <h2>1. Acceptance of Terms</h2>
      <p>
        By accessing or using <strong>The Billionaire Brother</strong> (the "Service", "we", "us", "our"), 
        you agree to be bound by these Terms of Service. If you do not agree to all of these terms, 
        you are prohibited from using the Service.
      </p>

      <h2>2. Description of Service</h2>
      <p>
        The Billionaire Brother is an artificial intelligence-driven platform featuring "Derek," a simulated business strategist persona. 
        The Service provides automated strategic analysis, decision auditing (Decision Scores), weekly action step checklists, 
        and general business framework generation based on user inputs.
      </p>
      <p>
        <strong>Note:</strong> All strategic guidance, recommendations, scores, and deliverables generated by the Service 
        are model-based estimates and pattern-matching simulations.
      </p>

      <h2>3. User Account and Security</h2>
      <p>
        To access the core features, you must create an account. You agree to:
      </p>
      <ul>
        <li>Provide accurate and complete information during registration.</li>
        <li>Maintain the security and confidentiality of your credentials.</li>
        <li>Notify us immediately of any unauthorized access to your account.</li>
        <li>Accept full responsibility for all activities that occur under your account.</li>
      </ul>

      <h2>4. Subscription, Billing, and Cancellations</h2>
      <p>
        Certain features of the Service are offered under paid subscription tiers (e.g., Brother Plan, Team Plan).
      </p>
      <ul>
        <li><strong>Billing:</strong> Subscriptions are billed in advance on a recurring monthly basis.</li>
        <li><strong>Cancellations:</strong> You can cancel your subscription at any time directly through your Account Settings. Your access to paid features will continue until the end of your current billing period.</li>
        <li><strong>Refunds:</strong> We offer a 14-day risk-free money-back guarantee for first-time subscribers. To request a refund, contact us within 14 days of your initial purchase.</li>
      </ul>

      <h2>5. Rules of Conduct</h2>
      <p>
        You agree not to use the Service to:
      </p>
      <ul>
        <li>Submit false, misleading, or fraudulent business information.</li>
        <li>Upload malicious code, viruses, or scrapers designed to disrupt or extract data from the Service.</li>
        <li>Input content that is unlawful, defamatory, harassing, or infringes on third-party intellectual property.</li>
        <li>Attempt to reverse-engineer, bypass rate limits, or exploit the underlying AI system architecture.</li>
      </ul>

      <h2>6. Intellectual Property & Deliverables</h2>
      <p>
        All rights, title, and interest in the software, brand name, logo, assets, and design system of The Billionaire Brother remain exclusive to us. 
        Any custom strategies, KPI plans, and action deliverables synthesized <strong>specifically for your business</strong> by Derek are yours to keep, reproduce, and execute.
      </p>

      <h2>7. Limitations of Liability & Disclaimers</h2>
      <p>
        <strong>DISCLAIMER OF WARRANTY:</strong> THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. WE MAKE NO WARRANTIES, 
        EXPRESSED OR IMPLIED, REGARDING THE ACCURACY, CORRECTNESS, OR RELEVANCE OF DEREK'S STRATEGY DIRECTIVES.
      </p>
      <p>
        <strong>NOT FINANCIAL OR LEGAL ADVICE:</strong> DEREK IS AN AI AGENT SIMULATION, NOT A LICENSED FINANCIAL ADVISOR, 
        ATTORNEY, CPA, OR SECURITIES BROKER. OUTPUTS DO NOT CONSTITUTE LEGAL, TAX, FINANCIAL, OR INVESTMENT ADVICE. 
        YOU AGREE TO USE YOUR OWN INDEPENDENT JUDGMENT AND CONSULT CERTIFIED PROFESSIONALS BEFORE EXECUTING STRATEGIES.
      </p>
      <p>
        <strong>LIMITATION OF LIABILITY:</strong> IN NO EVENT SHALL THE BILLIONAIRE BROTHER OR ITS AFFILIATES BE LIABLE FOR 
        ANY DIRECT, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL LOSSES, LOST PROFITS, OR BUSINESS DISRUPTIONS ARISING FROM 
        YOUR USE OF OR INABILITY TO USE THE SERVICE.
      </p>

      <h2>8. Changes to Terms</h2>
      <p>
        We reserve the right to modify these Terms of Service at any time. We will notify users of significant changes 
        via email or by posting a banner on our platform. Your continued use of the Service after changes are published 
        constitutes acceptance of the new terms.
      </p>

      <h2>9. Contact Us</h2>
      <p>
        If you have any questions regarding these Terms of Service, please dispatch a message through our 
        <a href="/contact" style={{ color: 'var(--gold-400)', textDecoration: 'underline', marginLeft: '4px' }}>Contact Strategist</a> portal.
      </p>
    </PolicyLayout>
  );
}
